import type { Tool } from './types';

export const initialTools: Omit<Tool, 'id'>[] = [
  {
    name: 'GenKit AI',
    description: 'A powerful framework for building, deploying, and monitoring AI-powered features with Node.js.',
    url: 'https://firebase.google.com/docs/genkit',
    categories: ['developer-tools', 'framework'],
    price: 'Free',
    easeOfUse: 'Intermediate',
    submittedBy: 'AI Enthusiast',
    justification: 'The best way to build production-ready AI apps.',
    upvotes: 100,
    downvotes: 5,
    imageUrl: 'https://placehold.co/600x400.png',
    submittedAt: new Date('2024-01-15T10:00:00Z'),
  },
  {
    name: 'ImageFX',
    description: "Generate stunning images from text descriptions with Google's advanced image generation model.",
    url: 'https://aistudio.google.com/app/imagefx',
    categories: ['image-generation', 'art'],
    price: 'Free',
    easeOfUse: 'Beginner',
    submittedBy: 'CreativePro',
    justification: 'Incredibly easy to use and produces high-quality images.',
    upvotes: 90,
    downvotes: 2,
    imageUrl: 'https://placehold.co/600x400.png',
    submittedAt: new Date('2024-02-20T14:30:00Z'),
  },
  {
    name: 'MusicFX',
    description: 'Create royalty-free music and sound effects using text prompts. Perfect for content creators.',
    url: 'https://aistudio.google.com/app/musicfx',
    categories: ['music-generation', 'audio'],
    price: 'Free',
    easeOfUse: 'Beginner',
    submittedBy: 'PodcasterPete',
    justification: "A game-changer for finding background music for my shows.",
    upvotes: 80,
    downvotes: 4,
    imageUrl: 'https://placehold.co/600x400.png',
    submittedAt: new Date('2024-03-05T09:00:00Z'),
  },
  {
    name: 'Notion AI',
    description: 'Integrates AI assistance directly into your Notion workspaces for summarizing, writing, and brainstorming.',
    url: 'https://www.notion.so/product/ai',
    categories: ['productivity', 'writing-assistant'],
    price: 'Paid',
    easeOfUse: 'Beginner',
    submittedBy: 'ProductivityHackr',
    justification: 'Seamlessly blends into my existing workflow and saves me hours.',
    upvotes: 98,
    downvotes: 6,
    imageUrl: 'https://placehold.co/600x400.png',
    submittedAt: new Date('2024-01-25T11:00:00Z'),
  },
    {
    name: 'RunwayML',
    description: 'An advanced AI video editor with features like text-to-video, inpainting, and motion tracking.',
    url: 'https://runwayml.com/',
    categories: ['video-generation', 'editing'],
    price: 'Freemium',
    easeOfUse: 'Intermediate',
    submittedBy: 'VideoVince',
    justification: 'The future of video editing. The AI tools are incredibly powerful.',
    upvotes: 88,
    downvotes: 3,
    imageUrl: 'https://placehold.co/600x400.png',
    submittedAt: new Date('2024-02-10T18:00:00Z'),
  },
  {
    name: 'Synthesia',
    description: 'Create professional videos with AI avatars and voiceovers in minutes, without cameras or microphones.',
    url: 'https://www.synthesia.io/',
    categories: ['video-generation', 'avatar'],
    price: 'Paid',
    easeOfUse: 'Beginner',
    submittedBy: 'CorporateTrainer',
    justification: 'Perfect for creating training materials quickly and consistently.',
    upvotes: 75,
    downvotes: 5,
    imageUrl: 'https://placehold.co/600x400.png',
    submittedAt: new Date('2024-03-12T16:45:00Z'),
  },
  {
    name: 'Copy.ai',
    description: "AI-powered copywriter that generates high-quality marketing copy, from blog posts to social media updates.",
    url: 'https://www.copy.ai/',
    categories: ['copywriting', 'marketing', 'seo'],
    price: 'Freemium',
    easeOfUse: 'Beginner',
    submittedBy: 'MarketerMary',
    justification: "Helps overcome writer's block and generates great ideas for campaigns.",
    upvotes: 92,
    downvotes: 3,
    imageUrl: 'https://placehold.co/600x400.png',
    submittedAt: new Date('2024-01-30T12:10:00Z'),
  },
  {
    name: 'Llama 3',
    description: "Meta's next-generation, open-source large language model, available for research and commercial use.",
    url: 'https://ai.meta.com/llama/',
    categories: ['llm', 'developer-tools', 'open-source'],
    price: 'Free',
    easeOfUse: 'Expert',
    submittedBy: 'OpenSourceDev',
    justification: 'A very capable open-source model that can be fine-tuned for specific tasks.',
    upvotes: 110,
    downvotes: 12,
    imageUrl: 'https://placehold.co/600x400.png',
    submittedAt: new Date('2024-04-01T08:00:00Z'),
  },
];
