steps:
# 1. Use the official Node.js 20 image to install dependencies.
- name: 'node:20'
  entrypoint: 'npm'
  args: ['install']

# 2. Use the same Node.js 20 image to build the Next.js app.
- name: 'node:20'
  entrypoint: 'npm'
  args: ['run', 'build']

# 3. Use the official firebase-tools builder to deploy to App Hosting.
- name: 'gcr.io/firebase-tools/firebase'
  args:
    - 'deploy'
    - '--only=apphosting'
    - '--project=ai-tool-explorer-txijl'
    - '--non-interactive'

options:
  # Use a more powerful machine to speed up the build
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
