# Something strange
steps:
# Step 1: Install project dependencies
- name: 'gcr.io/cloud-builders/node:20'
  args: ['npm', 'install']

# Step 2: Build the Next.js application for production
- name: 'gcr.io/cloud-builders/node:20'
  args: ['npm', 'run', 'build']

# Step 3: Run the deployment using the firebase-tools installed in node_modules
# This is more reliable than using a separate firebase-tools image.
- name: 'gcr.io/cloud-builders/node:20'
  args:
    - 'npm'
    - 'run'
    - 'firebase'
    - '--'
    - 'deploy'
    - '--only=apphosting'
    - '--project=ai-tool-explorer-txijl'
    - '--non-interactive'

options:
  # Use a more powerful machine to speed up the build
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
