steps:
  # Debug Step: Check Node.js version
  - name: 'gcr.io/cloud-builders/npm:20'
    entrypoint: 'node'
    args: ['-v']

  # Step 0: Install project dependencies using npm ci for deterministic builds
  - name: 'gcr.io/cloud-builders/npm:20'
    args: ['npm', 'ci']

  # Step 1: Run Linter (Quality Gate)
  - name: 'gcr.io/cloud-builders/npm:20'
    args: ['npm', 'run', 'lint']

  # Step 2: Run Type Checker (Quality Gate)
  - name: 'gcr.io/cloud-builders/npm:20'
    args: ['npm', 'run', 'typecheck']

  # Step 3: Build the Next.js application for production
  - name: 'gcr.io/cloud-builders/npm:20'
    args: ['npm', 'run', 'build', '--', '--no-lint']

  # Step 4: Run the deployment using the firebase-tools installed in node_modules
  # This is more reliable than using a separate firebase-tools image.
  - name: 'gcr.io/cloud-builders/npm:20'
    args:
      - 'npm'
      - 'run'
      - 'firebase'
      - '--'
      - 'deploy'
      - '--only=apphosting'
      - '--project=ai-tool-explorer-txijl'
      - '--non-interactive'

options:
  # Use a more powerful machine to speed up the build
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
