steps:
# 1. Use the official Node.js 20 image to install dependencies.
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

# 2. Use the same Node.js 20 image to build the Next.js app.
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']

# 3. Install firebase-tools and deploy.
# We use the npm builder to install firebase-tools, which is more reliable
# than pulling the gcr.io/firebase-tools/firebase image directly.
- name: 'gcr.io/cloud-builders/npm'
  args:
    - 'install'
    - '--global'
    - 'firebase-tools'
- name: 'node:20' # Use a node environment to ensure firebase can be found in the path
  entrypoint: 'firebase'
  args:
    - 'deploy'
    - '--only=apphosting'
    - '--project=ai-tool-explorer-txijl'
    - '--non-interactive'

options:
  # Use a more powerful machine to speed up the build
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
